import csv
import os
import subprocess
import threading
import time
from datetime import datetime, timedelta

from apps.route.models import Hazard, TrafficHazard

_OSRM_ARTIFACT_DIR = os.getenv("OSRM_DATA_DIR") or os.path.join(os.getcwd(), "osrm")
_OSRM_HAZARD_CSV = os.getenv("OSRM_HAZARD_CSV") or os.path.join(
    _OSRM_ARTIFACT_DIR, "hazard_penalties.csv"
)
_OSRM_HAZARD_LUA = os.getenv("OSRM_HAZARD_LUA") or os.path.join(
    _OSRM_ARTIFACT_DIR, "hazard_penalties.lua"
)
_OSRM_PROFILE_LUA = os.getenv("OSRM_PROFILE_LUA") or os.path.join(
    _OSRM_ARTIFACT_DIR, "car.lua"
)
_OSRM_PBF_PATH = os.getenv("OSRM_PBF_PATH") or os.path.join(
    _OSRM_ARTIFACT_DIR, "map.osm.pbf"
)
_OSRM_OSRM_PATH = os.getenv("OSRM_OSRM_PATH") or os.path.join(
    _OSRM_ARTIFACT_DIR, "map.osrm"
)
_OSRM_THREADS = int(os.getenv("OSRM_THREADS", "8"))
_OSRM_CUSTOMIZE_LOCK = threading.Lock()
_OSRM_CUSTOMIZE_RUNNING = False


def penalty_from_danger(danger_score):
    """Convert a danger score into an OSRM hazard penalty multiplier."""
    score = max(0.0, min(float(danger_score), 10.0))
    return 1.0 + score * score * 0.1


def _osrm_artifact_path(path_hint, fallback):
    """Resolve an OSRM artifact path and ensure its directory exists."""
    path = os.path.abspath(path_hint or fallback)
    directory = os.path.dirname(path) or "."
    os.makedirs(directory, exist_ok=True)
    return path


def _gather_penalties():
    """Gather active hazard and traffic penalties, keeping the highest value per edge."""
    hazards = (
        Hazard.query.filter_by(is_active=True)
        .with_entities(
            Hazard.osm_edge_id,
            Hazard.edge_id,
            Hazard.weight_penalty,
            Hazard.danger_score,
        )
        .all()
    )
    penalties = {}
    for osm_edge_id, edge_id, weight_penalty, danger_score in hazards:
        edge = osm_edge_id or edge_id
        if not edge:
            continue
        penalty = weight_penalty or penalty_from_danger(danger_score)
        if penalty and penalty > penalties.get(edge, 0.0):
            penalties[edge] = penalty

    cutoff = datetime.now() - timedelta(minutes=5)
    traffic_rows = (
        TrafficHazard.query.filter(TrafficHazard.updated_at >= cutoff)
        .with_entities(TrafficHazard.osm_edge_id, TrafficHazard.penalty)
        .all()
    )
    for edge, penalty in traffic_rows:
        if not edge or penalty is None:
            continue
        if penalty > penalties.get(edge, 0.0):
            penalties[edge] = penalty
    return penalties


def export_hazard_penalties_csv(csv_path=None):
    """Export the current hazard penalties into a CSV file for OSRM to read."""
    path = _osrm_artifact_path(csv_path, _OSRM_HAZARD_CSV)
    penalties = _gather_penalties()
    with open(path, "w", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(["edge_id", "penalty"])
        for edge in sorted(penalties):
            writer.writerow([edge, f"{penalties[edge]:.6f}"])
    return {"csv_path": path, "rows": len(penalties)}


def _hazard_lua_template(csv_path):
    """Return the Lua module that loads hazards from the given CSV."""
    csv_escaped = csv_path.replace("\\", "\\\\")
    return f"""-- Auto-generated by apps.route.hazard_pipeline.export_hazard_penalties_csv
-- Loads hazard penalties from CSV for use inside a custom OSRM profile.
local hazard_penalties = {{}}
local csv_path = "{csv_escaped}"

local function load_from_csv()
  local fh = io.open(csv_path, "r")
  if not fh then
    return
  end
  fh:read("*l") -- skip header
  for line in fh:lines() do
    local edge, penalty = line:match("([^,]+),([^,]+)")
    if edge and penalty then
      hazard_penalties[edge] = tonumber(penalty) or 0
    end
  end
  fh:close()
end

load_from_csv()

-- Usage inside your OSRM Lua profile:
--   local hazards = require("hazard_penalties").penalties
--   local p = hazards[edge_id]
--   if p and result.weight then result.weight = result.weight * p end
return {{{{
  penalties = hazard_penalties,
  apply = function(edge_id, weight, duration)
    local p = hazard_penalties[edge_id]
    if not p then
      return weight, duration
    end
    if weight then weight = weight * p end
    if duration then duration = duration * p end
    return weight, duration
  end
}}}}
"""


def render_osrm_hazard_profile(csv_path=None, lua_path=None):
    """Render the Lua profile that exposes the hazard penalty lookup table."""
    csv_abs = _osrm_artifact_path(csv_path, _OSRM_HAZARD_CSV)
    lua_abs = _osrm_artifact_path(lua_path, _OSRM_HAZARD_LUA)
    with open(lua_abs, "w") as fh:
        fh.write(_hazard_lua_template(csv_abs))
    return {"lua_path": lua_abs, "csv_path": csv_abs}


def export_osrm_hazard_artifacts(csv_path=None, lua_path=None):
    """Ensure hazard CSV and Lua artifacts are up to date and return their metadata."""
    csv_meta = export_hazard_penalties_csv(csv_path)
    lua_meta = render_osrm_hazard_profile(csv_meta["csv_path"], lua_path)
    payload = {"hazard_rows": csv_meta["rows"], **csv_meta, **lua_meta}
    return payload


def _run_osrm(cmd):
    """Run an OSRM CLI command under the artifact directory and raise on failure."""
    proc = subprocess.run(
        cmd,
        cwd=_OSRM_ARTIFACT_DIR,
        check=False,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"{' '.join(cmd)} failed: {proc.stderr.strip() or proc.stdout.strip()}"
        )
    return proc.stdout.strip()


def build_osrm_pipeline(pbf_path=None, profile_path=None, osrm_path=None, threads=None):
    """Build the OSRM dataset by extracting, partitioning, and customizing with hazards."""
    export_osrm_hazard_artifacts()
    profile = _osrm_artifact_path(profile_path, _OSRM_PROFILE_LUA)
    pbf = _osrm_artifact_path(pbf_path, _OSRM_PBF_PATH)
    osrm_file = _osrm_artifact_path(osrm_path, _OSRM_OSRM_PATH)
    t = threads or _OSRM_THREADS
    _run_osrm(["osrm-extract", "-p", profile, pbf])
    _run_osrm(["osrm-partition", osrm_file])
    _run_osrm(["osrm-customize", "-t", str(t), osrm_file])
    return {"pbf": pbf, "profile": profile, "osrm": osrm_file, "threads": t}


def trigger_osrm_customize(osrm_path=None, threads=None):
    """Run osrm-customize asynchronously after refreshing hazard artifacts."""
    osrm_file = _osrm_artifact_path(osrm_path, _OSRM_OSRM_PATH)
    if not os.path.exists(osrm_file):
        return False

    def _worker():
        global _OSRM_CUSTOMIZE_RUNNING
        with _OSRM_CUSTOMIZE_LOCK:
            if _OSRM_CUSTOMIZE_RUNNING:
                return
            _OSRM_CUSTOMIZE_RUNNING = True
        try:
            export_osrm_hazard_artifacts()
            _run_osrm(
                [
                    "osrm-customize",
                    "-t",
                    str(threads or _OSRM_THREADS),
                    osrm_file,
                ]
            )
        except Exception:
            pass
        finally:
            _OSRM_CUSTOMIZE_RUNNING = False

    threading.Thread(target=_worker, daemon=True).start()
    return True


class _CustomizeWorker:
    """Background worker that debounces repeated osrm-customize requests."""
    def __init__(self, cooldown_sec=None):
        self.cooldown = float(
            cooldown_sec or os.getenv("OSRM_CUSTOMIZE_DEBOUNCE", "2.0")
        )
        self._event = threading.Event()
        self._stop = threading.Event()
        self._thread = threading.Thread(target=self._loop, daemon=True)
        self._thread.start()

    def poke(self):
        """Signal the worker to run customize after the cooldown window."""
        self._event.set()
        return True

    def _loop(self):
        """Wait for poke events and kick off osrm-customize operations with a cooldown."""
        global _OSRM_CUSTOMIZE_RUNNING
        while not self._stop.is_set():
            if not self._event.wait(timeout=0.5):
                continue

            self._event.clear()
            deadline = time.time() + self.cooldown
            while time.time() < deadline and not self._stop.is_set():
                if self._event.wait(timeout=0.1):
                    self._event.clear()
                    deadline = time.time() + self.cooldown

            osrm_file = _osrm_artifact_path(None, _OSRM_OSRM_PATH)
            if not os.path.exists(osrm_file):
                continue

            try:
                export_osrm_hazard_artifacts()
                with _OSRM_CUSTOMIZE_LOCK:
                    if _OSRM_CUSTOMIZE_RUNNING:
                        continue
                    _OSRM_CUSTOMIZE_RUNNING = True
                try:
                    _run_osrm(["osrm-customize", "-t", str(_OSRM_THREADS), osrm_file])
                finally:
                    _OSRM_CUSTOMIZE_RUNNING = False
            except Exception:
                pass

    def stop(self):
        """Stop the background worker and wake any waiters to exit quickly."""
        self._stop.set()
        self._event.set()


_CUSTOMIZE_WORKER = _CustomizeWorker()


def schedule_osrm_customize():
    """Ask the background worker to perform osrm-customize using existing artifacts."""
    try:
        return _CUSTOMIZE_WORKER.poke()
    except Exception:
        return False
