"""empty message

Revision ID: 02c8b841fbfd
Revises: f134b32ef53c
Create Date: 2025-10-29 15:54:48.809262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02c8b841fbfd'
down_revision = 'f134b32ef53c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_target_type', sa.Enum('USER', 'POST', 'REPLY', name='reporttype'), nullable=False),
    sa.Column('report_target_id', sa.Integer(), nullable=False),
    sa.Column('report_reason', sa.String(length=255), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('user_id', 'report_target_type', 'report_target_id', name='unique_report_per_user')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_report_per_user'))

    op.drop_table('reports')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('report_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('report_target_type', mysql.ENUM('USER', 'POST', 'REPLY'), nullable=False),
    sa.Column('report_target_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('report_reason', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('report_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('reports_ibfk_1')),
    sa.PrimaryKeyConstraint('report_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_report_per_user'), ['user_id', 'report_target_type', 'report_target_id'], unique=True)

    op.drop_table('report')
    # ### end Alembic commands ###
