"""empty message

Revision ID: 0443f7542009
Revises: 
Create Date: 2025-11-04 10:34:24.559718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0443f7542009'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('histories', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('path_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('histories_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('histories_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'paths', ['path_id'], ['path_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.drop_column('history_id')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommend_point', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('risk_point', sa.Integer(), nullable=True))
        batch_op.drop_column('risk_level')
        batch_op.drop_column('is_danger')

    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('unique_mention'))
        batch_op.create_unique_constraint('unique_mention_target', ['mentioned_user_id', 'post_id', 'reply_id'])
        batch_op.drop_constraint(batch_op.f('mentions_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('mentions_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['post_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['mentioned_user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'replies', ['reply_id'], ['reply_id'], ondelete='CASCADE')
        batch_op.drop_column('content_type')
        batch_op.drop_column('object_id')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_counts', sa.Integer(), nullable=True))
        batch_op.drop_column('view_count')

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.BLOB(),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('reply_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('reply_images_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'replies', ['reply_id'], ['reply_id'])
        batch_op.drop_column('post_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('reply_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reply_images_ibfk_1'), 'posts', ['post_id'], ['post_id'])
        batch_op.drop_column('reply_id')

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.String(length=200),
               type_=sa.BLOB(),
               existing_nullable=True)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('view_counts')

    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('content_type', mysql.ENUM('POST', 'REPLY', 'SUBREPLY'), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mentions_ibfk_1'), 'users', ['mentioned_user_id'], ['user_id'])
        batch_op.create_foreign_key(batch_op.f('mentions_ibfk_2'), 'posts', ['post_id'], ['post_id'])
        batch_op.drop_constraint('unique_mention_target', type_='unique')
        batch_op.create_index(batch_op.f('unique_mention'), ['content_type', 'object_id', 'mentioned_user_id'], unique=True)
        batch_op.drop_column('reply_id')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_danger', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('risk_level', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('risk_point')
        batch_op.drop_column('recommend_point')

    with op.batch_alter_table('histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history_id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('histories_ibfk_2'), 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(batch_op.f('histories_ibfk_1'), 'paths', ['path_id'], ['path_id'])
        batch_op.alter_column('path_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
