"""Add CASCADE constraints and notification system

Revision ID: 0a0aaa28c4fc
Revises: 
Create Date: 2025-11-18 11:56:02.985764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a0aaa28c4fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 새 테이블 생성은 주석 처리 - 기존 테이블이 이미 존재할 수 있음
    # op.create_table('hazards',
    # sa.Column('hazard_id', sa.Integer(), nullable=False),
    # sa.Column('lat', sa.Float(), nullable=False),
    # sa.Column('lon', sa.Float(), nullable=False),
    # sa.Column('danger_score', sa.Float(), nullable=False),
    # sa.Column('is_active', sa.Boolean(), nullable=False),
    # sa.Column('edge_id', sa.String(length=64), nullable=True),
    # sa.Column('osm_edge_id', sa.String(length=64), nullable=True),
    # sa.Column('weight_penalty', sa.Float(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('hazard_id')
    # )
    # with op.batch_alter_table('hazards', schema=None) as batch_op:
    #     batch_op.create_index('idx_hazard_active_edge', ['is_active', 'edge_id'], unique=False)
    #     batch_op.create_index('idx_hazard_active_osm_edge', ['is_active', 'osm_edge_id'], unique=False)
    #     batch_op.create_index('idx_hazard_location', ['lat', 'lon'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_hazards_edge_id'), ['edge_id'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_hazards_is_active'), ['is_active'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_hazards_lat'), ['lat'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_hazards_lon'), ['lon'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_hazards_osm_edge_id'), ['osm_edge_id'], unique=False)

    # 이미 존재하는 테이블은 생성하지 않음
    # op.create_table('products',
    # sa.Column('product_id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=100), nullable=False),
    # sa.Column('description', sa.Text(), nullable=True),
    # sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    # sa.Column('stock', sa.Integer(), nullable=True),
    # sa.Column('is_active', sa.Boolean(), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.Column('updated_at', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('product_id')
    # )
    
    # 새 테이블 생성은 모두 주석 처리 - 기존 테이블 유지
    # op.create_table('favorites',
    # op.create_table('follow',
    # op.create_table('friend',
    # op.create_table('feed_items',
    
    # 기존 테이블 유지 - 삭제하지 않음
    # op.drop_table('histories')
    # op.drop_table('accident_reports')
    # op.drop_table('follows')
    # op.drop_table('friends')
    # op.drop_table('sight_types')
    # with op.batch_alter_table('reply_images', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('uuid'))
    # op.drop_table('reply_images')
    # op.drop_table('sights')
    # op.drop_table('locations')
    
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('category_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('images_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('images_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['post_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('my_paths', schema=None) as batch_op:
        batch_op.alter_column('path_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_my_paths_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'], ondelete='CASCADE')

    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('post_likes_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('post_likes_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['post_id'], ondelete='CASCADE')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('posts_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('replies_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('replies_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('replies_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'replies', ['parent_id'], ['reply_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['post_id'], ondelete='CASCADE')

    with op.batch_alter_table('reply_likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('reply_likes_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('reply_likes_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'replies', ['reply_id'], ['reply_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    # reports 테이블 구조 변경 주석 처리 - 기존 구조 유지
    # with op.batch_alter_table('reports', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('reporter_id', sa.Integer(), nullable=False))
    #     batch_op.add_column(sa.Column('target_type', sa.Enum('USER', 'POST', 'REPLY', name='reporttype'), nullable=False))
    #     batch_op.add_column(sa.Column('target_id', sa.Integer(), nullable=False))
    #     batch_op.add_column(sa.Column('reason', sa.String(length=255), nullable=False))
    #     batch_op.add_column(sa.Column('is_resolved', sa.Boolean(), nullable=True))
    #     batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
    #     batch_op.drop_constraint(batch_op.f('unique_report_per_user'), type_='unique')
    #     batch_op.create_unique_constraint('unique_report_per_user', ['reporter_id', 'target_type', 'target_id'])
    #     batch_op.drop_constraint(batch_op.f('reports_ibfk_1'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'users', ['reporter_id'], ['user_id'])
    #     batch_op.drop_column('result')
    #     batch_op.drop_column('report_reason')
    #     batch_op.drop_column('report_target_type')
    #     batch_op.drop_column('report_target_id')
    #     batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('report_target_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('report_target_type', mysql.ENUM('USER', 'POST', 'REPLY'), nullable=False))
        batch_op.add_column(sa.Column('report_reason', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('result', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reports_ibfk_1'), 'users', ['user_id'], ['user_id'])
        batch_op.drop_constraint('unique_report_per_user', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_report_per_user'), ['user_id', 'report_target_type', 'report_target_id'])
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('is_resolved')
        batch_op.drop_column('reason')
        batch_op.drop_column('target_id')
        batch_op.drop_column('target_type')
        batch_op.drop_column('reporter_id')

    with op.batch_alter_table('reply_likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reply_likes_ibfk_2'), 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(batch_op.f('reply_likes_ibfk_1'), 'replies', ['reply_id'], ['reply_id'])

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('replies_ibfk_2'), 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(batch_op.f('replies_ibfk_1'), 'posts', ['post_id'], ['post_id'])
        batch_op.create_foreign_key(batch_op.f('replies_ibfk_3'), 'replies', ['parent_id'], ['reply_id'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('posts_ibfk_1'), 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_likes_ibfk_1'), 'posts', ['post_id'], ['post_id'])
        batch_op.create_foreign_key(batch_op.f('post_likes_ibfk_2'), 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('my_paths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_my_paths_user_id'))
        batch_op.alter_column('path_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('images_ibfk_1'), 'posts', ['post_id'], ['post_id'])
        batch_op.create_foreign_key(batch_op.f('images_ibfk_2'), 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('category_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    op.create_table('locations',
    sa.Column('location_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('latitude', mysql.FLOAT(), nullable=False),
    sa.Column('longitude', mysql.FLOAT(), nullable=False),
    sa.Column('order_index', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('recommend_point', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('risk_point', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], name=op.f('locations_ibfk_1')),
    sa.PrimaryKeyConstraint('location_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sights',
    sa.Column('sight_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('latitude', mysql.FLOAT(), nullable=True),
    sa.Column('longitude', mysql.FLOAT(), nullable=True),
    sa.Column('sight_type_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sight_type_id'], ['sight_types.sight_type_id'], name=op.f('sights_ibfk_1')),
    sa.PrimaryKeyConstraint('sight_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('reply_images',
    sa.Column('image_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('reply_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('directory', mysql.TEXT(), nullable=False),
    sa.Column('original_image_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ext', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['reply_id'], ['replies.reply_id'], name=op.f('reply_images_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('reply_images_ibfk_2')),
    sa.PrimaryKeyConstraint('image_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('reply_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uuid'), ['uuid'], unique=True)

    op.create_table('sight_types',
    sa.Column('sight_type_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sight_type_name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('sight_type_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('friends',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('friend_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.user_id'], name=op.f('friends_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('friends_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'friend_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('follows',
    sa.Column('follower_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('following_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.user_id'], name=op.f('follows_ibfk_1')),
    sa.ForeignKeyConstraint(['following_id'], ['users.user_id'], name=op.f('follows_ibfk_2')),
    sa.PrimaryKeyConstraint('follower_id', 'following_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('accident_reports',
    sa.Column('report_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latitude', mysql.FLOAT(), nullable=True),
    sa.Column('longitude', mysql.FLOAT(), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('image', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('ai_label', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('accident_reports_ibfk_1')),
    sa.PrimaryKeyConstraint('report_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('histories',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('path_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['my_paths.path_id'], name=op.f('histories_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('histories_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'path_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('feed_items')
    op.drop_table('friend')
    op.drop_table('follow')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index('idx_user_favorites')

    op.drop_table('favorites')
    op.drop_table('products')
    with op.batch_alter_table('hazards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hazards_osm_edge_id'))
        batch_op.drop_index(batch_op.f('ix_hazards_lon'))
        batch_op.drop_index(batch_op.f('ix_hazards_lat'))
        batch_op.drop_index(batch_op.f('ix_hazards_is_active'))
        batch_op.drop_index(batch_op.f('ix_hazards_edge_id'))
        batch_op.drop_index('idx_hazard_location')
        batch_op.drop_index('idx_hazard_active_osm_edge')
        batch_op.drop_index('idx_hazard_active_edge')

    op.drop_table('hazards')
    # ### end Alembic commands ###
