"""empty message

Revision ID: 0be5af0de821
Revises: 9984f749a173
Create Date: 2025-11-12 11:40:25.453871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0be5af0de821'
down_revision = '9984f749a173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('risk_point')
        batch_op.drop_column('latitude')
        batch_op.drop_column('recommend_point')
        batch_op.drop_column('longitude')

    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentioner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['mentioner_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mentioner_id')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('recommend_point', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('latitude', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('risk_point', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
