"""empty message

Revision ID: 602ebadc1983
Revises: 62c2bbac714d
Create Date: 2025-10-31 11:03:51.665440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602ebadc1983'
down_revision = '62c2bbac714d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply_images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('reply_images_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'replies', ['reply_id'], ['reply_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reply_images_ibfk_3'), 'posts', ['reply_id'], ['post_id'])

    # ### end Alembic commands ###
