"""empty message

Revision ID: 62c2bbac714d
Revises: 0e4c0103f694
Create Date: 2025-10-31 11:02:26.028299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62c2bbac714d'
down_revision = '0e4c0103f694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('reply_images_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['reply_id'], ['post_id'])
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reply_images_ibfk_1'), 'posts', ['post_id'], ['post_id'])
        batch_op.drop_column('reply_id')

    # ### end Alembic commands ###
