"""empty message

Revision ID: 843e4e138e0b
Revises: 602ebadc1983
Create Date: 2025-11-03 14:22:23.925258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '843e4e138e0b'
down_revision = '602ebadc1983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommend_point', sa.Integer(), nullable=True))
        batch_op.drop_column('is_danger')

    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('unique_mention'))
        batch_op.create_unique_constraint('unique_mention_target', ['mentioned_user_id', 'post_id', 'reply_id'])
        batch_op.drop_constraint(batch_op.f('mentions_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('mentions_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'replies', ['reply_id'], ['reply_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['post_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['mentioned_user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.drop_column('object_id')
        batch_op.drop_column('content_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', mysql.ENUM('POST', 'REPLY', 'SUBREPLY'), nullable=False))
        batch_op.add_column(sa.Column('object_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mentions_ibfk_1'), 'users', ['mentioned_user_id'], ['user_id'])
        batch_op.create_foreign_key(batch_op.f('mentions_ibfk_2'), 'posts', ['post_id'], ['post_id'])
        batch_op.drop_constraint('unique_mention_target', type_='unique')
        batch_op.create_index(batch_op.f('unique_mention'), ['content_type', 'object_id', 'mentioned_user_id'], unique=True)
        batch_op.drop_column('reply_id')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_danger', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('recommend_point')

    # ### end Alembic commands ###
