"""empty message

Revision ID: 90939efb516a
Revises: 0a0aaa28c4fc
Create Date: 2025-11-19 13:17:44.822622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90939efb516a'
down_revision = '0a0aaa28c4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accident_reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('ai_label', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'friend_id', name='pk_friend_user_friend')
    )
    op.create_table('histories',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['my_paths.path_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'path_id')
    )
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_follow'))

    op.drop_table('follow')
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('unique_friend'))

    op.drop_table('friend')
    with op.batch_alter_table('hazards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_hazard_active_edge'))
        batch_op.drop_index(batch_op.f('idx_hazard_active_osm_edge'))
        batch_op.drop_index(batch_op.f('idx_hazard_location'))
        batch_op.drop_index(batch_op.f('ix_hazards_edge_id'))
        batch_op.drop_index(batch_op.f('ix_hazards_is_active'))
        batch_op.drop_index(batch_op.f('ix_hazards_lat'))
        batch_op.drop_index(batch_op.f('ix_hazards_lon'))
        batch_op.drop_index(batch_op.f('ix_hazards_osm_edge_id'))

    op.drop_table('hazards')
    op.drop_table('feed_items')
    op.drop_table('products')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_favorites'))
        batch_op.drop_index(batch_op.f('unique_user_favorite'))

    op.drop_table('favorites')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('category_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('images_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('images_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['post_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('my_paths', schema=None) as batch_op:
        batch_op.alter_column('path_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_my_paths_user_id'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notifications_ibfk_6'), type_='foreignkey')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('post_likes_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('post_likes_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['post_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('posts_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('replies_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('replies_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('replies_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'replies', ['parent_id'], ['reply_id'])
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['post_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('reply_likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('reply_likes_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('reply_likes_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'replies', ['reply_id'], ['reply_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('reply_likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reply_likes_ibfk_2'), 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('reply_likes_ibfk_1'), 'replies', ['reply_id'], ['reply_id'], ondelete='CASCADE')

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('replies_ibfk_1'), 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('replies_ibfk_2'), 'replies', ['parent_id'], ['reply_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('replies_ibfk_3'), 'posts', ['post_id'], ['post_id'], ondelete='CASCADE')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('posts_ibfk_3'), 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_likes_ibfk_2'), 'posts', ['post_id'], ['post_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('post_likes_ibfk_1'), 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('notifications_ibfk_6'), 'products', ['product_id'], ['product_id'], ondelete='CASCADE')

    with op.batch_alter_table('my_paths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_my_paths_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('path_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('images_ibfk_2'), 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('images_ibfk_1'), 'posts', ['post_id'], ['post_id'], ondelete='CASCADE')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('category_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    op.create_table('favorites',
    sa.Column('favorite_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_type', mysql.ENUM('STORY', 'ROUTE', 'REVIEW', 'REPORT', 'PRODUCT'), nullable=False),
    sa.Column('item_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('favorites_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('favorite_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_user_favorite'), ['user_id', 'item_type', 'item_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_user_favorites'), ['user_id', 'item_type'], unique=False)

    op.create_table('products',
    sa.Column('product_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('stock', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('feed_items',
    sa.Column('feed_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feed_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('related_post_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('related_reply_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('related_user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['related_post_id'], ['posts.post_id'], name=op.f('feed_items_ibfk_1')),
    sa.ForeignKeyConstraint(['related_reply_id'], ['replies.reply_id'], name=op.f('feed_items_ibfk_2')),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.user_id'], name=op.f('feed_items_ibfk_3')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('feed_items_ibfk_4')),
    sa.PrimaryKeyConstraint('feed_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('hazards',
    sa.Column('hazard_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lat', mysql.FLOAT(), nullable=False),
    sa.Column('lon', mysql.FLOAT(), nullable=False),
    sa.Column('danger_score', mysql.FLOAT(), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('edge_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('osm_edge_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('weight_penalty', mysql.FLOAT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('hazard_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('hazards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hazards_osm_edge_id'), ['osm_edge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hazards_lon'), ['lon'], unique=False)
        batch_op.create_index(batch_op.f('ix_hazards_lat'), ['lat'], unique=False)
        batch_op.create_index(batch_op.f('ix_hazards_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_hazards_edge_id'), ['edge_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_hazard_location'), ['lat', 'lon'], unique=False)
        batch_op.create_index(batch_op.f('idx_hazard_active_osm_edge'), ['is_active', 'osm_edge_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_hazard_active_edge'), ['is_active', 'edge_id'], unique=False)

    op.create_table('friend',
    sa.Column('friend_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('friend_user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['friend_user_id'], ['users.user_id'], name=op.f('friend_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('friend_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('friend_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_friend'), ['user_id', 'friend_user_id'], unique=True)

    op.create_table('follow',
    sa.Column('follow_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('follower_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('following_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.user_id'], name=op.f('follow_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.user_id'], name=op.f('follow_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follow_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_follow'), ['follower_id', 'following_id'], unique=True)

    op.drop_table('histories')
    op.drop_table('friends')
    op.drop_table('follows')
    op.drop_table('accident_reports')
    # ### end Alembic commands ###
