"""empty message

Revision ID: c7fffd295062
Revises: 843e4e138e0b
Create Date: 2025-11-03 14:56:01.252546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7fffd295062'
down_revision = '843e4e138e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_counts', sa.Integer(), nullable=True))
        batch_op.drop_column('view_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('view_counts')

    # ### end Alembic commands ###
