"""empty message

Revision ID: e529be6f3c62
Revises: f97fb33ece5d
Create Date: 2025-11-11 09:49:28.248048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e529be6f3c62'
down_revision = 'f97fb33ece5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['post_id'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('posts_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('location')

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               type_=sa.Text(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               nullable=True)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('posts_ibfk_2'), 'locations', ['location'], ['location_id'])

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
