"""empty message

Revision ID: f97fb33ece5d
Revises: 
Create Date: 2025-11-05 14:30:37.664320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97fb33ece5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentions',
    sa.Column('mention_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mentioned_user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('reply_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=True),
    sa.CheckConstraint('(post_id IS NOT NULL AND reply_id IS NULL) OR (post_id IS NULL AND reply_id IS NOT NULL)', name='check_one_target'),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_id'], ['replies.reply_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mention_id'),
    sa.UniqueConstraint('mentioned_user_id', 'post_id', 'reply_id', name='unique_mention_target')
    )
    op.create_table('reply_images',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('directory', sa.Text(), nullable=False),
    sa.Column('original_image_name', sa.String(length=255), nullable=False),
    sa.Column('ext', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reply_id'], ['replies.reply_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('image_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('reply_likes',
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reply_id'], ['replies.reply_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('reply_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply_likes')
    op.drop_table('reply_images')
    op.drop_table('mentions')
    # ### end Alembic commands ###
